Repository sharemindteam/sharemind-server, pull requests merged in 2024-06, with the labels that each got.

#190 refactor: 회원가입 로직 간소화
  src/main/java/com/example/sharemind/auth/application/AuthService.java
  src/main/java/com/example/sharemind/auth/application/AuthServiceImpl.java
  src/main/java/com/example/sharemind/auth/dto/request/AuthFindIdRequest.java
  src/main/java/com/example/sharemind/auth/dto/request/AuthSignUpRequest.java
  src/main/java/com/example/sharemind/auth/exception/AuthErrorCode.java
  src/main/java/com/example/sharemind/auth/presentation/AuthController.java
  src/main/java/com/example/sharemind/customer/application/CustomerService.java
  src/main/java/com/example/sharemind/customer/application/CustomerServiceImpl.java
  src/main/java/com/example/sharemind/customer/domain/Customer.java
  src/main/java/com/example/sharemind/customer/repository/CustomerRepository.java
  src/main/java/com/example/sharemind/email/content/EmailType.java
Labels: refactor

#191 refactor: 공개상담 인기순 조회 로직 수정
  src/main/java/com/example/sharemind/post/application/PostService.java
  src/main/java/com/example/sharemind/post/application/PostServiceImpl.java
  src/main/java/com/example/sharemind/post/dto/response/PostGetPopularityResponse.java
  src/main/java/com/example/sharemind/post/presentation/PostController.java
  src/main/java/com/example/sharemind/post/repository/PostCustomRepository.java
  src/main/java/com/example/sharemind/post/repository/PostCustomRepositoryImpl.java
  src/main/java/com/example/sharemind/post/repository/PostRepository.java
Labels: refactor

#193 fix: 들을 준비가 된 상담사 리스트 수정
  src/main/java/com/example/sharemind/counselor/application/CounselorServiceImpl.java
  src/main/java/com/example/sharemind/counselor/dto/response/CounselorGetListResponse.java
  src/main/java/com/example/sharemind/counselor/presentation/CounselorController.java
  src/main/java/com/example/sharemind/global/constants/Constants.java
  src/main/java/com/example/sharemind/searchWord/application/SearchWordServiceImpl.java
Labels: fix

#197 feat: 특정 상담사 프로필 대기 상태로 수정하는 기능 구현
  .gitignore
  build.gradle
  src/main/java/com/example/sharemind/admin/application/AdminService.java
  src/main/java/com/example/sharemind/admin/application/AdminServiceImpl.java
  src/main/java/com/example/sharemind/admin/dto/response/CounselorGetByNicknameOrEmailResponse.java
  src/main/java/com/example/sharemind/admin/presentation/AdminController.java
  src/main/java/com/example/sharemind/counselor/application/CounselorService.java
  src/main/java/com/example/sharemind/counselor/application/CounselorServiceImpl.java
  src/main/java/com/example/sharemind/counselor/repository/CounselorRepository.java
  src/test/java/com/example/sharemind/admin/application/AdminServiceTest.java
  src/test/java/com/example/sharemind/counselor/CounselorDataFactory.java
  src/test/java/com/example/sharemind/counselor/domain/CounselorTest.java
  src/test/java/com/example/sharemind/counselor/repository/CounselorRepositoryTest.java
  src/test/java/com/example/sharemind/customer/CustomerDataFactory.java
Labels: feature

#205 fix: 들을 준비된 마인더들 무한 스크롤 문제 해결
  src/main/java/com/example/sharemind/counselor/application/CounselorServiceImpl.java
  src/main/java/com/example/sharemind/counselor/dto/response/CounselorGetForConsultResponse.java
Labels: fix
