Repository sharemindteam/sharemind-server, pull requests merged in 2024-03, with the labels that each got.

#133 feat: 일대다 비공개 상담 결제 여부 처리하는 어드민 api 구현
  src/main/java/com/example/sharemind/admin/application/AdminService.java
  src/main/java/com/example/sharemind/admin/application/AdminServiceImpl.java
  src/main/java/com/example/sharemind/admin/dto/response/PostGetUnpaidPrivateResponse.java
  src/main/java/com/example/sharemind/admin/presentation/AdminController.java
  src/main/java/com/example/sharemind/global/exception/CustomExceptionHandler.java
  src/main/java/com/example/sharemind/post/application/PostService.java
  src/main/java/com/example/sharemind/post/application/PostServiceImpl.java
  src/main/java/com/example/sharemind/post/content/PostStatus.java
  src/main/java/com/example/sharemind/post/domain/Post.java
  src/main/java/com/example/sharemind/post/dto/request/PostCreateRequest.java
  src/main/java/com/example/sharemind/post/exception/PostErrorCode.java
  src/main/java/com/example/sharemind/post/exception/PostException.java
  src/main/java/com/example/sharemind/post/presentation/PostController.java
  src/main/java/com/example/sharemind/post/repository/PostRepository.java
Labels: feature

#135 fix: 비밀번호 찾기 로직 변경
  src/main/java/com/example/sharemind/auth/application/AuthService.java
  src/main/java/com/example/sharemind/auth/application/AuthServiceImpl.java
  src/main/java/com/example/sharemind/auth/dto/request/AuthFindIdRequest.java
  src/main/java/com/example/sharemind/auth/dto/request/AuthFindPasswordRequest.java
  src/main/java/com/example/sharemind/auth/presentation/AuthController.java
  src/main/java/com/example/sharemind/chat/application/ChatTaskScheduler.java
Labels: fix

#140 fix:새로운 채팅 생성시 dto 누락 문제 해결
  src/main/java/com/example/sharemind/chat/application/ChatServiceImpl.java
  src/main/java/com/example/sharemind/chat/dto/response/ChatNotifyEventResponse.java
  src/main/java/com/example/sharemind/consult/repository/ConsultRepository.java
  src/main/java/com/example/sharemind/global/websocket/WebSocketEventListener.java
Labels: fix

#138 feat: 일대다 상담 질문 저장 구현
  src/main/java/com/example/sharemind/post/application/PostService.java
  src/main/java/com/example/sharemind/post/application/PostServiceImpl.java
  src/main/java/com/example/sharemind/post/domain/Post.java
  src/main/java/com/example/sharemind/post/dto/request/PostUpdateRequest.java
  src/main/java/com/example/sharemind/post/exception/PostErrorCode.java
  src/main/java/com/example/sharemind/post/exception/PostException.java
  src/main/java/com/example/sharemind/post/presentation/PostController.java
Labels: feature

#142 fix:새로운 채팅 생성시 dto 누락 문제 해결
  src/main/java/com/example/sharemind/admin/application/AdminServiceImpl.java
  src/main/java/com/example/sharemind/chat/dto/response/ChatNotifyEventResponse.java
  src/main/java/com/example/sharemind/global/websocket/WebSocketEventListener.java
Labels: fix

#144 fix: 상담사 최신 채팅 3개 불러오는 부분 수정
  src/main/java/com/example/sharemind/chat/application/ChatConsultService.java
  src/main/java/com/example/sharemind/chatMessage/dto/response/ChatMessageGetResponse.java
  src/main/java/com/example/sharemind/chatMessage/utils/ChatMessageUtil.java
  src/main/java/com/example/sharemind/global/dto/response/ChatLetterGetResponse.java
Labels: fix

#146 feat: 일대다 상담 질문 조회 구현
  build.gradle
  src/main/java/com/example/sharemind/global/config/QueryDslConfig.java
  src/main/java/com/example/sharemind/post/application/PostService.java
  src/main/java/com/example/sharemind/post/application/PostServiceImpl.java
  src/main/java/com/example/sharemind/post/content/PostStatus.java
  src/main/java/com/example/sharemind/post/domain/Post.java
  src/main/java/com/example/sharemind/post/dto/request/PostUpdateRequest.java
  src/main/java/com/example/sharemind/post/dto/response/PostGetIsSavedResponse.java
  src/main/java/com/example/sharemind/post/dto/response/PostGetResponse.java
  src/main/java/com/example/sharemind/post/presentation/PostController.java
  src/main/java/com/example/sharemind/post/repository/PostCustomRepository.java
  src/main/java/com/example/sharemind/post/repository/PostCustomRepositoryImpl.java
  src/main/java/com/example/sharemind/post/repository/PostRepository.java
Labels: feature

#149 refactor: 일대다 상담 질문 단건 조회 리팩토링
  src/main/java/com/example/sharemind/global/config/SecurityConfig.java
  src/main/java/com/example/sharemind/post/application/PostService.java
  src/main/java/com/example/sharemind/post/application/PostServiceImpl.java
  src/main/java/com/example/sharemind/post/domain/Post.java
  src/main/java/com/example/sharemind/post/dto/response/PostGetResponse.java
  src/main/java/com/example/sharemind/post/exception/PostErrorCode.java
  src/main/java/com/example/sharemind/post/presentation/PostController.java
Labels: refactor

#150 feat: 일대다 상담 미답변 질문 조회 및 답변 기능 구현
  src/main/java/com/example/sharemind/comment/application/CommentService.java
  src/main/java/com/example/sharemind/comment/application/CommentServiceImpl.java
  src/main/java/com/example/sharemind/comment/domain/Comment.java
  src/main/java/com/example/sharemind/comment/dto/request/CommentCreateRequest.java
  src/main/java/com/example/sharemind/comment/dto/response/CommentGetResponse.java
  src/main/java/com/example/sharemind/comment/exception/CommentErrorCode.java
  src/main/java/com/example/sharemind/comment/exception/CommentException.java
  src/main/java/com/example/sharemind/comment/presentation/CommentController.java
  src/main/java/com/example/sharemind/comment/repository/CommentRepository.java
  src/main/java/com/example/sharemind/global/config/SecurityConfig.java
  src/main/java/com/example/sharemind/global/exception/CustomExceptionHandler.java
  src/main/java/com/example/sharemind/post/application/PostService.java
  src/main/java/com/example/sharemind/post/application/PostServiceImpl.java
  src/main/java/com/example/sharemind/post/domain/Post.java
  src/main/java/com/example/sharemind/post/exception/PostErrorCode.java
  src/main/java/com/example/sharemind/post/presentation/PostController.java
  src/main/java/com/example/sharemind/post/repository/PostRepository.java
Labels: feature

#155 feat: 일대다 상담 좋아요 기능 구현
  src/main/java/com/example/sharemind/comment/application/CommentService.java
  src/main/java/com/example/sharemind/comment/application/CommentServiceImpl.java
  src/main/java/com/example/sharemind/comment/domain/Comment.java
  src/main/java/com/example/sharemind/comment/dto/response/CommentGetResponse.java
  src/main/java/com/example/sharemind/comment/exception/CommentErrorCode.java
  src/main/java/com/example/sharemind/comment/repository/CommentRepository.java
  src/main/java/com/example/sharemind/commentLike/application/CommentLikeService.java
  src/main/java/com/example/sharemind/commentLike/application/CommentLikeServiceImpl.java
  src/main/java/com/example/sharemind/commentLike/domain/CommentLike.java
  src/main/java/com/example/sharemind/commentLike/exception/CommentLikeErrorCode.java
  src/main/java/com/example/sharemind/commentLike/exception/CommentLikeException.java
  src/main/java/com/example/sharemind/commentLike/presentation/CommentLikeController.java
  src/main/java/com/example/sharemind/commentLike/repository/CommentLikeRepository.java
  src/main/java/com/example/sharemind/global/exception/CustomExceptionHandler.java
  src/main/java/com/example/sharemind/post/application/PostService.java
  src/main/java/com/example/sharemind/post/application/PostServiceImpl.java
  src/main/java/com/example/sharemind/post/domain/Post.java
  src/main/java/com/example/sharemind/post/dto/response/PostGetListResponse.java
  src/main/java/com/example/sharemind/post/dto/response/PostGetResponse.java
  src/main/java/com/example/sharemind/post/presentation/PostController.java
  src/main/java/com/example/sharemind/postLike/application/PostLikeService.java
  src/main/java/com/example/sharemind/postLike/application/PostLikeServiceImpl.java
  src/main/java/com/example/sharemind/postLike/domain/PostLike.java
  src/main/java/com/example/sharemind/postLike/exception/PostLikeErrorCode.java
  src/main/java/com/example/sharemind/postLike/exception/PostLikeException.java
  src/main/java/com/example/sharemind/postLike/presentation/PostLikeController.java
  src/main/java/com/example/sharemind/postLike/repository/PostLikeRepository.java
Labels: feature

#158 feat: 구매자 사이드 일대다 상담 댓글 조회 구현
  src/main/java/com/example/sharemind/comment/application/CommentService.java
  src/main/java/com/example/sharemind/comment/application/CommentServiceImpl.java
  src/main/java/com/example/sharemind/comment/presentation/CommentController.java
  src/main/java/com/example/sharemind/global/config/SecurityConfig.java
  src/main/java/com/example/sharemind/post/application/PostServiceImpl.java
Labels: feature

#159 feat: 일대다 상담 미답변 질문 상담사 사이드 조회 구현
  src/main/java/com/example/sharemind/comment/application/CommentServiceImpl.java
  src/main/java/com/example/sharemind/comment/repository/CommentCustomRepository.java
  src/main/java/com/example/sharemind/comment/repository/CommentCustomRepositoryImpl.java
  src/main/java/com/example/sharemind/comment/repository/CommentRepository.java
  src/main/java/com/example/sharemind/global/constants/Constants.java
  src/main/java/com/example/sharemind/post/application/PostService.java
  src/main/java/com/example/sharemind/post/application/PostServiceImpl.java
  src/main/java/com/example/sharemind/post/domain/Post.java
  src/main/java/com/example/sharemind/post/dto/response/PostGetCounselorListResponse.java
  src/main/java/com/example/sharemind/post/presentation/PostController.java
  src/main/java/com/example/sharemind/post/repository/PostRepository.java
Labels: feature

#160 fix: 상담사 자신에게 상담 신청 못하도록 수정
  src/main/java/com/example/sharemind/chat/application/ChatTaskScheduler.java
  src/main/java/com/example/sharemind/comment/application/CommentServiceImpl.java
  src/main/java/com/example/sharemind/comment/presentation/CommentController.java
  src/main/java/com/example/sharemind/consult/application/ConsultServiceImpl.java
  src/main/java/com/example/sharemind/consult/presentation/ConsultController.java
  src/main/java/com/example/sharemind/counselor/application/CounselorService.java
  src/main/java/com/example/sharemind/counselor/application/CounselorServiceImpl.java
  src/main/java/com/example/sharemind/counselor/exception/CounselorErrorCode.java
Labels: fix

#166 feat: 공개 상담 검색 기능 구현
  src/main/java/com/example/sharemind/counselor/application/CounselorService.java
  src/main/java/com/example/sharemind/counselor/application/CounselorServiceImpl.java
  src/main/java/com/example/sharemind/global/config/SecurityConfig.java
  src/main/java/com/example/sharemind/post/application/PostService.java
  src/main/java/com/example/sharemind/post/application/PostServiceImpl.java
  src/main/java/com/example/sharemind/post/content/PostListSortType.java
  src/main/java/com/example/sharemind/post/exception/PostErrorCode.java
  src/main/java/com/example/sharemind/post/repository/PostCustomRepository.java
  src/main/java/com/example/sharemind/post/repository/PostCustomRepositoryImpl.java
  src/main/java/com/example/sharemind/searchWord/application/SearchWordService.java
  src/main/java/com/example/sharemind/searchWord/application/SearchWordServiceImpl.java
  src/main/java/com/example/sharemind/searchWord/dto/request/SearchWordCounselorFindRequest.java
  src/main/java/com/example/sharemind/searchWord/dto/request/SearchWordPostFindRequest.java
  src/main/java/com/example/sharemind/searchWord/presentation/SearchWordController.java
Labels: feature
