Repository sharemindteam/sharemind-server, pull requests merged in 2024-01, with the labels that each got.

#9 feat: 상담 신청 구현
  src/main/java/com/example/sharemind/auth/application/AuthServiceImpl.java
  src/main/java/com/example/sharemind/auth/exception/AuthErrorCode.java
  src/main/java/com/example/sharemind/auth/exception/AuthException.java
  src/main/java/com/example/sharemind/consult/application/ConsultService.java
  src/main/java/com/example/sharemind/consult/application/ConsultServiceImpl.java
  src/main/java/com/example/sharemind/consult/domain/Consult.java
  src/main/java/com/example/sharemind/consult/dto/request/ConsultCreateRequest.java
  src/main/java/com/example/sharemind/consult/dto/response/ConsultCreateResponse.java
  src/main/java/com/example/sharemind/consult/presentation/ConsultController.java
  src/main/java/com/example/sharemind/consult/repository/ConsultRepository.java
  src/main/java/com/example/sharemind/counselor/domain/ConsultCost.java
  src/main/java/com/example/sharemind/counselor/domain/Counselor.java
  src/main/java/com/example/sharemind/counselor/exception/CounselorErrorCode.java
  src/main/java/com/example/sharemind/counselor/exception/CounselorException.java
  src/main/java/com/example/sharemind/counselor/repository/CounselorRepository.java
  src/main/java/com/example/sharemind/customer/domain/Customer.java
  src/main/java/com/example/sharemind/customer/domain/Role.java
  src/main/java/com/example/sharemind/customer/exception/CustomerErrorCode.java
  src/main/java/com/example/sharemind/customer/exception/CustomerException.java
  src/main/java/com/example/sharemind/global/config/SecurityConfig.java
  src/main/java/com/example/sharemind/global/content/ConsultCategory.java
  src/main/java/com/example/sharemind/global/content/ConsultStyle.java
  src/main/java/com/example/sharemind/global/content/ConsultType.java
  src/main/java/com/example/sharemind/global/exception/CustomExceptionHandler.java
  src/main/java/com/example/sharemind/global/exception/CustomExceptionResponse.java
  src/main/java/com/example/sharemind/global/exception/GlobalErrorCode.java
  src/main/java/com/example/sharemind/global/exception/GlobalException.java
  src/main/java/com/example/sharemind/global/exception/GlobalExceptionHandler.java
  src/main/java/com/example/sharemind/global/jwt/CustomUserDetails.java
  src/main/java/com/example/sharemind/global/jwt/TokenProvider.java
Labels: feature

#11 feat: 어드민 페이지 구현
  src/main/java/com/example/sharemind/admin/application/AdminService.java
  src/main/java/com/example/sharemind/admin/application/AdminServiceImpl.java
  src/main/java/com/example/sharemind/admin/dto/response/ConsultsGetUnpaidResponse.java
  src/main/java/com/example/sharemind/admin/presentation/AdminController.java
  src/main/java/com/example/sharemind/consult/domain/Consult.java
  src/main/java/com/example/sharemind/consult/exception/ConsultErrorCode.java
  src/main/java/com/example/sharemind/consult/exception/ConsultException.java
  src/main/java/com/example/sharemind/consult/repository/ConsultRepository.java
  src/main/java/com/example/sharemind/customer/domain/Role.java
  src/main/java/com/example/sharemind/global/config/SecurityConfig.java
  src/main/java/com/example/sharemind/global/exception/CustomExceptionHandler.java
Labels: feature

#15 feat: 비실시간 상담 및 메시지 생성 구현
  src/main/java/com/example/sharemind/admin/application/AdminServiceImpl.java
  src/main/java/com/example/sharemind/consult/application/ConsultService.java
  src/main/java/com/example/sharemind/consult/application/ConsultServiceImpl.java
  src/main/java/com/example/sharemind/consult/content/RefundStatus.java
  src/main/java/com/example/sharemind/consult/domain/Consult.java
  src/main/java/com/example/sharemind/consult/exception/ConsultErrorCode.java
  src/main/java/com/example/sharemind/consult/exception/ConsultException.java
  src/main/java/com/example/sharemind/counselor/content/ConsultCost.java
  src/main/java/com/example/sharemind/counselor/content/ConsultStyle.java
  src/main/java/com/example/sharemind/counselor/domain/Counselor.java
  src/main/java/com/example/sharemind/customer/content/Role.java
  src/main/java/com/example/sharemind/customer/domain/Customer.java
  src/main/java/com/example/sharemind/global/content/ConsultType.java
  src/main/java/com/example/sharemind/global/exception/CustomExceptionHandler.java
  src/main/java/com/example/sharemind/global/jwt/TokenProvider.java
  src/main/java/com/example/sharemind/letter/application/LetterService.java
  src/main/java/com/example/sharemind/letter/application/LetterServiceImpl.java
  src/main/java/com/example/sharemind/letter/content/LetterStatus.java
  src/main/java/com/example/sharemind/letter/domain/Letter.java
  src/main/java/com/example/sharemind/letter/exception/LetterErrorCode.java
  src/main/java/com/example/sharemind/letter/exception/LetterException.java
  src/main/java/com/example/sharemind/letter/repository/LetterRepository.java
  src/main/java/com/example/sharemind/nonRealtimeConsult/content/NonRealtimeConsultStatus.java
  src/main/java/com/example/sharemind/nonRealtimeConsult/domain/NonRealtimeConsult.java
  src/main/java/com/example/sharemind/nonRealtimeMessage/application/LetterMessageService.java
  src/main/java/com/example/sharemind/nonRealtimeMessage/application/LetterMessageServiceImpl.java
  src/main/java/com/example/sharemind/nonRealtimeMessage/content/LetterMessageType.java
  src/main/java/com/example/sharemind/nonRealtimeMessage/domain/LetterMessage.java
  src/main/java/com/example/sharemind/nonRealtimeMessage/domain/NonRealtimeMessage.java
  src/main/java/com/example/sharemind/nonRealtimeMessage/dto/request/LetterMessageCreateRequest.java
  src/main/java/com/example/sharemind/nonRealtimeMessage/exception/LetterMessageErrorCode.java
  src/main/java/com/example/sharemind/nonRealtimeMessage/exception/LetterMessageException.java
  src/main/java/com/example/sharemind/nonRealtimeMessage/presentation/LetterMessageController.java
  src/main/java/com/example/sharemind/nonRealtimeMessage/repository/LetterMessageRepository.java
Labels: feature

#19 feat: swagger 적용
  build.gradle
  src/main/java/com/example/sharemind/global/config/SecurityConfig.java
  src/main/java/com/example/sharemind/global/config/SwaggerConfig.java
Labels: feature

#17 feat: 비실시간 상담 임시저장/제출 구현
  src/main/java/com/example/sharemind/global/content/ConsultCategory.java
  src/main/java/com/example/sharemind/global/exception/CustomExceptionHandler.java
  src/main/java/com/example/sharemind/global/exception/GlobalErrorCode.java
  src/main/java/com/example/sharemind/letter/application/LetterService.java
  src/main/java/com/example/sharemind/letter/application/LetterServiceImpl.java
  src/main/java/com/example/sharemind/letter/domain/Letter.java
  src/main/java/com/example/sharemind/letter/dto/response/LetterGetCounselorCategoriesResponse.java
  src/main/java/com/example/sharemind/letter/dto/response/LetterGetNicknameCategoryResponse.java
  src/main/java/com/example/sharemind/letter/exception/LetterErrorCode.java
  src/main/java/com/example/sharemind/letter/presentation/LetterController.java
  src/main/java/com/example/sharemind/letterMessage/application/LetterMessageService.java
  src/main/java/com/example/sharemind/letterMessage/application/LetterMessageServiceImpl.java
  src/main/java/com/example/sharemind/letterMessage/content/LetterMessageType.java
  src/main/java/com/example/sharemind/letterMessage/domain/LetterMessage.java
  src/main/java/com/example/sharemind/letterMessage/dto/request/LetterMessageCreateFirstRequest.java
  src/main/java/com/example/sharemind/letterMessage/dto/request/LetterMessageCreateRequest.java
  src/main/java/com/example/sharemind/letterMessage/dto/request/LetterMessageUpdateFirstRequest.java
  src/main/java/com/example/sharemind/letterMessage/dto/request/LetterMessageUpdateRequest.java
  src/main/java/com/example/sharemind/letterMessage/dto/response/LetterMessageGetDeadlineResponse.java
  src/main/java/com/example/sharemind/letterMessage/dto/response/LetterMessageGetIsSavedResponse.java
  src/main/java/com/example/sharemind/letterMessage/dto/response/LetterMessageGetResponse.java
  src/main/java/com/example/sharemind/letterMessage/exception/LetterMessageErrorCode.java
  src/main/java/com/example/sharemind/letterMessage/exception/LetterMessageException.java
  src/main/java/com/example/sharemind/letterMessage/presentation/LetterMessageController.java
  src/main/java/com/example/sharemind/letterMessage/repository/LetterMessageRepository.java
  src/main/java/com/example/sharemind/nonRealtimeMessage/application/LetterMessageService.java
  src/main/java/com/example/sharemind/nonRealtimeMessage/application/LetterMessageServiceImpl.java
  src/main/java/com/example/sharemind/nonRealtimeMessage/content/LetterMessageType.java
  src/main/java/com/example/sharemind/nonRealtimeMessage/domain/LetterMessage.java
  src/main/java/com/example/sharemind/nonRealtimeMessage/exception/LetterMessageErrorCode.java
  src/main/java/com/example/sharemind/nonRealtimeMessage/presentation/LetterMessageController.java
  src/main/java/com/example/sharemind/nonRealtimeMessage/repository/LetterMessageRepository.java
Labels: feature

#24 refactor: swagger 설명 추가
  .gitignore
  src/main/java/com/example/sharemind/admin/dto/response/ConsultsGetUnpaidResponse.java
  src/main/java/com/example/sharemind/admin/presentation/AdminController.java
  src/main/java/com/example/sharemind/auth/dto/request/AuthReissueRequest.java
  src/main/java/com/example/sharemind/auth/dto/request/AuthSignInRequest.java
  src/main/java/com/example/sharemind/auth/dto/request/AuthSignUpRequest.java
  src/main/java/com/example/sharemind/auth/dto/response/TokenDto.java
  src/main/java/com/example/sharemind/auth/presentation/AuthController.java
  src/main/java/com/example/sharemind/consult/dto/request/ConsultCreateRequest.java
  src/main/java/com/example/sharemind/consult/dto/response/ConsultCreateResponse.java
  src/main/java/com/example/sharemind/consult/presentation/ConsultController.java
  src/main/java/com/example/sharemind/consult/repository/ConsultRepository.java
  src/main/java/com/example/sharemind/global/exception/CustomExceptionResponse.java
  src/main/java/com/example/sharemind/letter/application/LetterService.java
  src/main/java/com/example/sharemind/letter/application/LetterServiceImpl.java
  src/main/java/com/example/sharemind/letter/dto/response/LetterGetCounselorCategoriesResponse.java
  src/main/java/com/example/sharemind/letter/dto/response/LetterGetNicknameCategoryResponse.java
  src/main/java/com/example/sharemind/letter/dto/response/LetterGetResponse.java
  src/main/java/com/example/sharemind/letter/presentation/LetterController.java
  src/main/java/com/example/sharemind/letterMessage/dto/request/LetterMessageCreateFirstRequest.java
  src/main/java/com/example/sharemind/letterMessage/dto/request/LetterMessageCreateRequest.java
  src/main/java/com/example/sharemind/letterMessage/dto/request/LetterMessageUpdateFirstRequest.java
  src/main/java/com/example/sharemind/letterMessage/dto/request/LetterMessageUpdateRequest.java
  src/main/java/com/example/sharemind/letterMessage/dto/response/LetterMessageGetDeadlineResponse.java
  src/main/java/com/example/sharemind/letterMessage/dto/response/LetterMessageGetIsSavedResponse.java
  src/main/java/com/example/sharemind/letterMessage/dto/response/LetterMessageGetResponse.java
  src/main/java/com/example/sharemind/letterMessage/presentation/LetterMessageController.java
Labels: refactor

#20 feat: 채팅 웹소켓 jwt 인증 및 채팅 api 일부 구현
  src/main/java/com/example/sharemind/auth/exception/AuthErrorCode.java
  src/main/java/com/example/sharemind/chat/application/ChatService.java
  src/main/java/com/example/sharemind/chat/application/ChatServiceImpl.java
  src/main/java/com/example/sharemind/chat/content/ChatStatus.java
  src/main/java/com/example/sharemind/chat/domain/Chat.java
  src/main/java/com/example/sharemind/chat/dto/response/ChatInfoGetResponse.java
  src/main/java/com/example/sharemind/chat/exception/ChatErrorCode.java
  src/main/java/com/example/sharemind/chat/exception/ChatException.java
  src/main/java/com/example/sharemind/chat/presentation/ChatController.java
  src/main/java/com/example/sharemind/chat/repository/ChatRepository.java
  src/main/java/com/example/sharemind/chatMessage/application/ChatMessageService.java
  src/main/java/com/example/sharemind/chatMessage/application/ChatMessageServiceImpl.java
  src/main/java/com/example/sharemind/chatMessage/domain/ChatMessage.java
  src/main/java/com/example/sharemind/chatMessage/dto/request/ChatMessageCreateRequest.java
  src/main/java/com/example/sharemind/chatMessage/dto/response/ChatMessageResponse.java
  src/main/java/com/example/sharemind/chatMessage/presentation/ChatMessageController.java
  src/main/java/com/example/sharemind/chatMessage/repository/ChatMessageRepository.java
  src/main/java/com/example/sharemind/consult/domain/Consult.java
  src/main/java/com/example/sharemind/consult/repository/ConsultRepository.java
  src/main/java/com/example/sharemind/counselor/application/CounselorService.java
  src/main/java/com/example/sharemind/counselor/application/CounselorServiceImpl.java
  src/main/java/com/example/sharemind/global/config/SecurityConfig.java
  src/main/java/com/example/sharemind/global/config/WebSocketBrokerConfig.java
  src/main/java/com/example/sharemind/global/exception/CustomExceptionHandler.java
  src/main/java/com/example/sharemind/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/sharemind/global/websocket/StompErrorHandler.java
  src/main/java/com/example/sharemind/global/websocket/StompPreHandler.java
  src/main/java/com/example/sharemind/realtimeConsult/application/RealtimeConsultService.java
  src/main/java/com/example/sharemind/realtimeConsult/application/RealtimeConsultServiceImpl.java
  src/main/java/com/example/sharemind/realtimeConsult/content/RealtimeConsultStatus.java
  src/main/java/com/example/sharemind/realtimeConsult/domain/RealtimeConsult.java
  src/main/java/com/example/sharemind/realtimeConsult/dto/request/ChattingRequest.java
  src/main/java/com/example/sharemind/realtimeConsult/presentation/RealtimeChattingController.java
  src/main/java/com/example/sharemind/realtimeMessage/domain/RealtimeMessage.java
  src/main/resources/static/app.js
  src/main/resources/static/chat.html
  src/main/resources/static/index.html
Labels: feature

#29 release: 채팅 swagger 적용까지 배포
  src/main/java/com/example/sharemind/auth/exception/AuthErrorCode.java
  src/main/java/com/example/sharemind/chat/application/ChatService.java
  src/main/java/com/example/sharemind/chat/application/ChatServiceImpl.java
  src/main/java/com/example/sharemind/chat/content/ChatStatus.java
  src/main/java/com/example/sharemind/chat/domain/Chat.java
  src/main/java/com/example/sharemind/chat/dto/response/ChatInfoGetResponse.java
  src/main/java/com/example/sharemind/chat/exception/ChatErrorCode.java
  src/main/java/com/example/sharemind/chat/exception/ChatException.java
  src/main/java/com/example/sharemind/chat/presentation/ChatController.java
  src/main/java/com/example/sharemind/chat/repository/ChatRepository.java
  src/main/java/com/example/sharemind/chatMessage/application/ChatMessageService.java
  src/main/java/com/example/sharemind/chatMessage/application/ChatMessageServiceImpl.java
  src/main/java/com/example/sharemind/chatMessage/domain/ChatMessage.java
  src/main/java/com/example/sharemind/chatMessage/dto/request/ChatMessageCreateRequest.java
  src/main/java/com/example/sharemind/chatMessage/dto/response/ChatMessageResponse.java
  src/main/java/com/example/sharemind/chatMessage/presentation/ChatMessageController.java
  src/main/java/com/example/sharemind/chatMessage/repository/ChatMessageRepository.java
  src/main/java/com/example/sharemind/consult/domain/Consult.java
  src/main/java/com/example/sharemind/consult/repository/ConsultRepository.java
  src/main/java/com/example/sharemind/counselor/application/CounselorService.java
  src/main/java/com/example/sharemind/counselor/application/CounselorServiceImpl.java
  src/main/java/com/example/sharemind/global/config/SecurityConfig.java
  src/main/java/com/example/sharemind/global/config/WebSocketBrokerConfig.java
  src/main/java/com/example/sharemind/global/exception/CustomExceptionHandler.java
  src/main/java/com/example/sharemind/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/sharemind/global/websocket/StompErrorHandler.java
  src/main/java/com/example/sharemind/global/websocket/StompPreHandler.java
  src/main/java/com/example/sharemind/realtimeConsult/application/RealtimeConsultService.java
  src/main/java/com/example/sharemind/realtimeConsult/application/RealtimeConsultServiceImpl.java
  src/main/java/com/example/sharemind/realtimeConsult/content/RealtimeConsultStatus.java
  src/main/java/com/example/sharemind/realtimeConsult/domain/RealtimeConsult.java
  src/main/java/com/example/sharemind/realtimeConsult/dto/request/ChattingRequest.java
  src/main/java/com/example/sharemind/realtimeConsult/presentation/RealtimeChattingController.java
  src/main/java/com/example/sharemind/realtimeMessage/domain/RealtimeMessage.java
  src/main/resources/static/app.js
  src/main/resources/static/chat.html
  src/main/resources/static/index.html
Labels: release

#35 #23 fix: swagger cors 에러 해결
  src/main/java/com/example/sharemind/global/config/SwaggerConfig.java
Labels: fix

#37 #23 fix: swagger cors 에러 해결
  src/main/java/com/example/sharemind/global/config/SecurityConfig.java
  src/main/java/com/example/sharemind/global/config/SwaggerConfig.java
Labels: fix

#38 swagger cors 에러 해결
  src/main/java/com/example/sharemind/global/config/SecurityConfig.java
  src/main/java/com/example/sharemind/global/config/SwaggerConfig.java
Labels: release

#39 #23 fix: swagger cors 에러 해결
  src/main/java/com/example/sharemind/global/config/SwaggerConfig.java
Labels: fix

#40 swagger cors 에러 해결
  src/main/java/com/example/sharemind/global/config/SwaggerConfig.java
Labels: release

#41 release: 이메일 인증 api 배포
  build.gradle
  src/main/java/com/example/sharemind/customer/application/CustomerService.java
  src/main/java/com/example/sharemind/customer/application/CustomerServiceImpl.java
  src/main/java/com/example/sharemind/email/application/EmailService.java
  src/main/java/com/example/sharemind/email/application/EmailServiceImpl.java
  src/main/java/com/example/sharemind/email/dto/request/EmailPostCodeRequest.java
  src/main/java/com/example/sharemind/email/dto/request/EmailPostRequest.java
  src/main/java/com/example/sharemind/email/exception/EmailErrorCode.java
  src/main/java/com/example/sharemind/email/exception/EmailException.java
  src/main/java/com/example/sharemind/email/presentation/EmailController.java
  src/main/java/com/example/sharemind/global/config/SecurityConfig.java
  src/main/java/com/example/sharemind/global/exception/CustomExceptionHandler.java
Labels: release

#42 ci/cd 기준 브랜치 develop로 변경
  .ebextensions/00-makeFiles.config
  .github/workflows/deploy.yml
  .platform/nginx/nginx.conf
  Procfile
  build.gradle
Labels: release

#44 feat: ci/cd 기준 브랜치 develop로 변경
  .github/workflows/deploy.yml
Labels: feature

#46 feat: 편지 목록/상태 조회 구현
  src/main/java/com/example/sharemind/admin/presentation/AdminController.java
  src/main/java/com/example/sharemind/auth/presentation/AuthController.java
  src/main/java/com/example/sharemind/consult/application/ConsultService.java
  src/main/java/com/example/sharemind/consult/application/ConsultServiceImpl.java
  src/main/java/com/example/sharemind/consult/repository/ConsultRepository.java
  src/main/java/com/example/sharemind/letter/application/LetterService.java
  src/main/java/com/example/sharemind/letter/application/LetterServiceImpl.java
  src/main/java/com/example/sharemind/letter/content/LetterSortType.java
  src/main/java/com/example/sharemind/letter/domain/Letter.java
  src/main/java/com/example/sharemind/letter/dto/response/LetterGetResponse.java
  src/main/java/com/example/sharemind/letter/exception/LetterErrorCode.java
  src/main/java/com/example/sharemind/letter/presentation/LetterController.java
  src/main/java/com/example/sharemind/letterMessage/application/LetterMessageService.java
  src/main/java/com/example/sharemind/letterMessage/application/LetterMessageServiceImpl.java
  src/main/java/com/example/sharemind/letterMessage/content/LetterMessageType.java
  src/main/java/com/example/sharemind/letterMessage/domain/LetterMessage.java
  src/main/java/com/example/sharemind/letterMessage/dto/response/LetterMessageGetDeadlineResponse.java
  src/main/java/com/example/sharemind/letterMessage/dto/response/LetterMessageGetIsSavedResponse.java
  src/main/java/com/example/sharemind/letterMessage/dto/response/LetterMessageGetRecentTypeResponse.java
  src/main/java/com/example/sharemind/letterMessage/dto/response/LetterMessageGetResponse.java
  src/main/java/com/example/sharemind/letterMessage/exception/LetterMessageErrorCode.java
  src/main/java/com/example/sharemind/letterMessage/presentation/LetterMessageController.java
  src/main/java/com/example/sharemind/letterMessage/repository/LetterMessageRepository.java
Labels: feature

#50 feature: 실시간 상담 jwt 적용 및 실시간 채팅 관련 api 구현
  src/main/java/com/example/sharemind/admin/application/AdminServiceImpl.java
  src/main/java/com/example/sharemind/chat/application/ChatService.java
  src/main/java/com/example/sharemind/chat/application/ChatServiceImpl.java
  src/main/java/com/example/sharemind/chat/application/ChatTaskScheduler.java
  src/main/java/com/example/sharemind/chat/content/ChatWebsocketStatus.java
  src/main/java/com/example/sharemind/chat/domain/Chat.java
  src/main/java/com/example/sharemind/chat/domain/ChatCreateEvent.java
  src/main/java/com/example/sharemind/chat/domain/ChatUpdateStatusEvent.java
  src/main/java/com/example/sharemind/chat/dto/request/ChatStatusUpdateRequest.java
  src/main/java/com/example/sharemind/chat/dto/response/ChatCreateEventResponse.java
  src/main/java/com/example/sharemind/chat/dto/response/ChatGetStatusResponse.java
  src/main/java/com/example/sharemind/chat/dto/response/ChatInfoGetResponse.java
  src/main/java/com/example/sharemind/chat/dto/response/ChatUpdateStatusResponse.java
  src/main/java/com/example/sharemind/chat/exception/ChatErrorCode.java
  src/main/java/com/example/sharemind/chat/presentation/ChatController.java
  src/main/java/com/example/sharemind/chatMessage/application/ChatMessageServiceImpl.java
  src/main/java/com/example/sharemind/chatMessage/dto/response/ChatMessageResponse.java
  src/main/java/com/example/sharemind/chatMessage/presentation/ChatMessageController.java
  src/main/java/com/example/sharemind/consult/application/ConsultService.java
  src/main/java/com/example/sharemind/consult/application/ConsultServiceImpl.java
  src/main/java/com/example/sharemind/consult/domain/Consult.java
  src/main/java/com/example/sharemind/consult/repository/ConsultRepository.java
  src/main/java/com/example/sharemind/global/config/RedisConfig.java
  src/main/java/com/example/sharemind/global/config/SecurityConfig.java
  src/main/java/com/example/sharemind/global/config/WebSocketBrokerConfig.java
  src/main/java/com/example/sharemind/global/constants/Constants.java
  src/main/java/com/example/sharemind/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/sharemind/global/websocket/StompPreHandler.java
  src/main/java/com/example/sharemind/global/websocket/WebSocketEventListener.java
  src/main/resources/static/app.js
  src/main/resources/static/chat.html
  src/main/resources/static/counselor.html
  src/main/resources/static/customer.html
  src/main/resources/static/index.html
  src/main/resources/static/roomSelection.html
Labels: feature

#54 refactor: 채팅/편지 리스트 조회 response 형식 통일
  src/main/java/com/example/sharemind/global/dto/response/ChatLetterGetResponse.java
  src/main/java/com/example/sharemind/letter/application/LetterService.java
  src/main/java/com/example/sharemind/letter/application/LetterServiceImpl.java
  src/main/java/com/example/sharemind/letter/dto/response/LetterGetResponse.java
  src/main/java/com/example/sharemind/letter/presentation/LetterController.java
Labels: refactor

#57 refactor: 채팅 목록 부분 response 통일
  src/main/java/com/example/sharemind/chat/application/ChatService.java
  src/main/java/com/example/sharemind/chat/application/ChatServiceImpl.java
  src/main/java/com/example/sharemind/chat/dto/response/ChatInfoGetResponse.java
  src/main/java/com/example/sharemind/chat/presentation/ChatController.java
  src/main/java/com/example/sharemind/global/dto/response/ChatLetterGetResponse.java
  src/main/java/com/example/sharemind/global/utils/TimeUtil.java
  src/main/java/com/example/sharemind/letter/dto/response/LetterGetResponse.java
Labels: refactor

#56 feat: 상담사 인증 구현
  src/main/java/com/example/sharemind/counselor/application/CounselorService.java
  src/main/java/com/example/sharemind/counselor/application/CounselorServiceImpl.java
  src/main/java/com/example/sharemind/counselor/domain/Counselor.java
  src/main/java/com/example/sharemind/counselor/exception/CounselorErrorCode.java
  src/main/java/com/example/sharemind/counselor/presentation/CounselorController.java
  src/main/java/com/example/sharemind/customer/domain/Customer.java
Labels: feature

#60 fix: 회원가입 시 이메일 인증 로직 변경
  src/main/java/com/example/sharemind/auth/repository/RefreshTokenRepository.java
  src/main/java/com/example/sharemind/email/application/EmailServiceImpl.java
  src/main/java/com/example/sharemind/email/exception/EmailErrorCode.java
  src/main/java/com/example/sharemind/email/presentation/EmailController.java
  src/main/java/com/example/sharemind/global/config/RedisConfig.java
  src/main/java/com/example/sharemind/global/jwt/TokenProvider.java
Labels: fix

#61 feat: 상담사 프로필 수정 구현
  src/main/java/com/example/sharemind/counselor/application/CounselorService.java
  src/main/java/com/example/sharemind/counselor/application/CounselorServiceImpl.java
  src/main/java/com/example/sharemind/counselor/content/ConsultStyle.java
  src/main/java/com/example/sharemind/counselor/content/DayOfWeek.java
  src/main/java/com/example/sharemind/counselor/content/ProfileStatus.java
  src/main/java/com/example/sharemind/counselor/domain/ConsultCost.java
  src/main/java/com/example/sharemind/counselor/domain/ConsultTime.java
  src/main/java/com/example/sharemind/counselor/domain/Counselor.java
  src/main/java/com/example/sharemind/counselor/dto/request/CounselorUpdateProfileRequest.java
  src/main/java/com/example/sharemind/counselor/exception/CounselorErrorCode.java
  src/main/java/com/example/sharemind/counselor/presentation/CounselorController.java
Labels: feature

#62 feat: 상담사 프로필 심사 관련 어드민 기능 구현
  src/main/java/com/example/sharemind/admin/application/AdminService.java
  src/main/java/com/example/sharemind/admin/application/AdminServiceImpl.java
  src/main/java/com/example/sharemind/admin/dto/response/CounselorGetPendingResponse.java
  src/main/java/com/example/sharemind/admin/presentation/AdminController.java
  src/main/java/com/example/sharemind/counselor/application/CounselorService.java
  src/main/java/com/example/sharemind/counselor/application/CounselorServiceImpl.java
  src/main/java/com/example/sharemind/counselor/domain/Counselor.java
  src/main/java/com/example/sharemind/counselor/exception/CounselorErrorCode.java
  src/main/java/com/example/sharemind/counselor/repository/CounselorRepository.java
  src/main/java/com/example/sharemind/customer/application/CustomerService.java
  src/main/java/com/example/sharemind/customer/application/CustomerServiceImpl.java
  src/main/java/com/example/sharemind/customer/domain/Customer.java
  src/main/java/com/example/sharemind/customer/exception/CustomerException.java
  src/main/java/com/example/sharemind/customer/repository/CustomerRepository.java
Labels: feature

#69 fix: 이메일 인증 api 리턴 타입 변경
  src/main/java/com/example/sharemind/email/application/EmailService.java
  src/main/java/com/example/sharemind/email/application/EmailServiceImpl.java
  src/main/java/com/example/sharemind/email/dto/response/EmailGetSendCountResponse.java
  src/main/java/com/example/sharemind/email/presentation/EmailController.java
Labels: fix

#64 feat: 상담사 내 정보/프로필 정보 조회 구현
  src/main/java/com/example/sharemind/admin/application/AdminService.java
  src/main/java/com/example/sharemind/admin/application/AdminServiceImpl.java
  src/main/java/com/example/sharemind/admin/presentation/AdminController.java
  src/main/java/com/example/sharemind/counselor/application/CounselorService.java
  src/main/java/com/example/sharemind/counselor/application/CounselorServiceImpl.java
  src/main/java/com/example/sharemind/counselor/content/ProfileStatus.java
  src/main/java/com/example/sharemind/counselor/domain/Counselor.java
  src/main/java/com/example/sharemind/counselor/dto/request/CounselorUpdateProfileRequest.java
  src/main/java/com/example/sharemind/counselor/dto/response/CounselorGetInfoResponse.java
  src/main/java/com/example/sharemind/counselor/dto/response/CounselorGetProfileResponse.java
  src/main/java/com/example/sharemind/counselor/presentation/CounselorController.java
Labels: feature

#66 feat: 홈화면 검색어 api 구현
  src/main/java/com/example/sharemind/admin/application/AdminServiceImpl.java
  src/main/java/com/example/sharemind/counselor/application/CounselorService.java
  src/main/java/com/example/sharemind/counselor/application/CounselorServiceImpl.java
  src/main/java/com/example/sharemind/counselor/domain/Counselor.java
  src/main/java/com/example/sharemind/counselor/dto/response/CounselorGetResponse.java
  src/main/java/com/example/sharemind/counselor/repository/CounselorRepository.java
  src/main/java/com/example/sharemind/searchWord/application/SearchWordService.java
  src/main/java/com/example/sharemind/searchWord/application/SearchWordServiceImpl.java
  src/main/java/com/example/sharemind/searchWord/domain/SearchWord.java
  src/main/java/com/example/sharemind/searchWord/dto/request/SearchWordDeleteRequest.java
  src/main/java/com/example/sharemind/searchWord/dto/request/SearchWordFindRequest.java
  src/main/java/com/example/sharemind/searchWord/presentation/SearchWordController.java
  src/main/java/com/example/sharemind/searchWord/repository/SearchWordRepository.java
  src/main/java/com/example/sharemind/wishlist/application/WishListService.java
  src/main/java/com/example/sharemind/wishlist/application/WishListServiceImpl.java
  src/main/java/com/example/sharemind/wishlist/repository/WishListRepository.java
  src/main/resources/data.sql
Labels: feature

#71 feat: 리뷰 생성/작성 구현
  src/main/java/com/example/sharemind/chat/domain/Chat.java
  src/main/java/com/example/sharemind/consult/domain/Consult.java
  src/main/java/com/example/sharemind/counselor/application/CounselorServiceImpl.java
  src/main/java/com/example/sharemind/counselor/domain/Counselor.java
  src/main/java/com/example/sharemind/counselor/dto/response/CounselorGetInfoResponse.java
  src/main/java/com/example/sharemind/counselor/exception/CounselorErrorCode.java
  src/main/java/com/example/sharemind/counselor/presentation/CounselorController.java
  src/main/java/com/example/sharemind/counselor/repository/CounselorRepository.java
  src/main/java/com/example/sharemind/global/dto/response/ChatLetterGetResponse.java
  src/main/java/com/example/sharemind/global/exception/CustomExceptionHandler.java
  src/main/java/com/example/sharemind/letter/domain/Letter.java
  src/main/java/com/example/sharemind/letter/dto/response/LetterGetResponse.java
  src/main/java/com/example/sharemind/review/application/ReviewService.java
  src/main/java/com/example/sharemind/review/application/ReviewServiceImpl.java
  src/main/java/com/example/sharemind/review/domain/Review.java
  src/main/java/com/example/sharemind/review/dto/request/ReviewSaveRequest.java
  src/main/java/com/example/sharemind/review/exception/ReviewErrorCode.java
  src/main/java/com/example/sharemind/review/exception/ReviewException.java
  src/main/java/com/example/sharemind/review/presentation/ReviewController.java
  src/main/java/com/example/sharemind/review/repository/ReviewRepository.java
Labels: feature

#75 feat: 리뷰 조회 구현
  src/main/java/com/example/sharemind/consult/application/ConsultServiceImpl.java
  src/main/java/com/example/sharemind/consult/presentation/ConsultController.java
  src/main/java/com/example/sharemind/counselor/application/CounselorServiceImpl.java
  src/main/java/com/example/sharemind/counselor/exception/CounselorErrorCode.java
  src/main/java/com/example/sharemind/counselor/repository/CounselorRepository.java
  src/main/java/com/example/sharemind/global/config/SecurityConfig.java
  src/main/java/com/example/sharemind/global/dto/response/ChatLetterGetResponse.java
  src/main/java/com/example/sharemind/global/utils/TimeUtil.java
  src/main/java/com/example/sharemind/review/application/ReviewService.java
  src/main/java/com/example/sharemind/review/application/ReviewServiceImpl.java
  src/main/java/com/example/sharemind/review/dto/response/ReviewGetResponse.java
  src/main/java/com/example/sharemind/review/dto/response/ReviewGetShortResponse.java
  src/main/java/com/example/sharemind/review/presentation/ReviewController.java
  src/main/java/com/example/sharemind/review/repository/ReviewRepository.java
Labels: feature

#77 feat: 상담사 총 리뷰 수, 평점 업데이트 로직 구현
  src/main/java/com/example/sharemind/auth/dto/request/AuthSignUpRequest.java
  src/main/java/com/example/sharemind/consult/dto/response/ConsultCreateResponse.java
  src/main/java/com/example/sharemind/counselor/application/CounselorServiceImpl.java
  src/main/java/com/example/sharemind/counselor/domain/Counselor.java
  src/main/java/com/example/sharemind/counselor/dto/response/CounselorGetInfoResponse.java
  src/main/java/com/example/sharemind/counselor/repository/CounselorRepository.java
  src/main/java/com/example/sharemind/customer/domain/Customer.java
  src/main/java/com/example/sharemind/letter/dto/response/LetterGetCounselorCategoriesResponse.java
  src/main/java/com/example/sharemind/review/domain/Review.java
  src/main/java/com/example/sharemind/review/dto/response/ReviewGetShortResponse.java
  src/main/java/com/example/sharemind/searchWord/presentation/SearchWordController.java
Labels: feature

#79 feat: 결제 엔티티 생성
  src/main/java/com/example/sharemind/admin/application/AdminServiceImpl.java
  src/main/java/com/example/sharemind/chat/domain/Chat.java
  src/main/java/com/example/sharemind/consult/application/ConsultService.java
  src/main/java/com/example/sharemind/consult/application/ConsultServiceImpl.java
  src/main/java/com/example/sharemind/consult/content/ConsultStatus.java
  src/main/java/com/example/sharemind/consult/domain/Consult.java
  src/main/java/com/example/sharemind/consult/presentation/ConsultController.java
  src/main/java/com/example/sharemind/consult/repository/ConsultRepository.java
  src/main/java/com/example/sharemind/counselor/application/CounselorService.java
  src/main/java/com/example/sharemind/counselor/application/CounselorServiceImpl.java
  src/main/java/com/example/sharemind/counselor/dto/response/CounselorGetForConsultResponse.java
  src/main/java/com/example/sharemind/counselor/exception/CounselorErrorCode.java
  src/main/java/com/example/sharemind/counselor/presentation/CounselorController.java
  src/main/java/com/example/sharemind/letter/domain/Letter.java
  src/main/java/com/example/sharemind/payment/content/PaymentCounselorStatus.java
  src/main/java/com/example/sharemind/payment/content/PaymentCustomerStatus.java
  src/main/java/com/example/sharemind/payment/domain/Payment.java
Labels: feature

#80 feat: 채팅방 대화 api 생성
  src/main/java/com/example/sharemind/chat/application/ChatService.java
  src/main/java/com/example/sharemind/chat/application/ChatServiceImpl.java
  src/main/java/com/example/sharemind/chat/application/ChatTaskScheduler.java
  src/main/java/com/example/sharemind/chat/content/ChatStatus.java
  src/main/java/com/example/sharemind/chat/content/ChatWebsocketStatus.java
  src/main/java/com/example/sharemind/chat/domain/Chat.java
  src/main/java/com/example/sharemind/chat/dto/response/ChatCreateEventResponse.java
  src/main/java/com/example/sharemind/chat/dto/response/ChatGetStatusResponse.java
  src/main/java/com/example/sharemind/chat/exception/ChatErrorCode.java
  src/main/java/com/example/sharemind/chat/presentation/ChatController.java
  src/main/java/com/example/sharemind/chatMessage/application/ChatMessageService.java
  src/main/java/com/example/sharemind/chatMessage/application/ChatMessageServiceImpl.java
  src/main/java/com/example/sharemind/chatMessage/dto/response/ChatMessageGetResponse.java
  src/main/java/com/example/sharemind/chatMessage/dto/response/ChatMessageWebSocketResponse.java
  src/main/java/com/example/sharemind/chatMessage/presentation/ChatMessageController.java
  src/main/java/com/example/sharemind/chatMessage/repository/ChatMessageRepository.java
  src/main/java/com/example/sharemind/counselor/application/CounselorService.java
  src/main/java/com/example/sharemind/counselor/application/CounselorServiceImpl.java
  src/main/java/com/example/sharemind/counselor/dto/response/CounselorGetBannerResponse.java
  src/main/java/com/example/sharemind/counselor/dto/response/CounselorGetBaseResponse.java
  src/main/java/com/example/sharemind/counselor/dto/response/CounselorGetListResponse.java
  src/main/java/com/example/sharemind/counselor/presentation/CounselorController.java
  src/main/java/com/example/sharemind/counselor/utils/CounselorUtil.java
  src/main/java/com/example/sharemind/global/content/ChatLetterSortType.java
  src/main/java/com/example/sharemind/global/exception/GlobalErrorCode.java
  src/main/java/com/example/sharemind/letter/application/LetterServiceImpl.java
  src/main/java/com/example/sharemind/letter/content/LetterSortType.java
  src/main/resources/static/counselor.html
  src/main/resources/static/customer.html
Labels: feature

#84 feat: 구매자 임시저장 카테고리 조회, 상담사 권한 설정 구현
  src/main/java/com/example/sharemind/global/config/SecurityConfig.java
  src/main/java/com/example/sharemind/global/utils/TimeUtil.java
  src/main/java/com/example/sharemind/letter/application/LetterService.java
  src/main/java/com/example/sharemind/letter/application/LetterServiceImpl.java
  src/main/java/com/example/sharemind/letter/presentation/LetterController.java
Labels: feature

#81 feat: 상담사 리스트 api 구현
  src/main/java/com/example/sharemind/chat/presentation/ChatController.java
  src/main/java/com/example/sharemind/chatMessage/presentation/ChatMessageController.java
  src/main/java/com/example/sharemind/counselor/application/CounselorService.java
  src/main/java/com/example/sharemind/counselor/application/CounselorServiceImpl.java
  src/main/java/com/example/sharemind/counselor/dto/request/CounselorGetRequest.java
  src/main/java/com/example/sharemind/counselor/presentation/CounselorController.java
  src/main/java/com/example/sharemind/counselor/repository/CounselorRepository.java
  src/main/java/com/example/sharemind/global/config/SecurityConfig.java
Labels: feature

#85 feat: 편지 환불 로직 구현
  src/main/java/com/example/sharemind/SharemindApplication.java
  src/main/java/com/example/sharemind/consult/content/ConsultStatus.java
  src/main/java/com/example/sharemind/consult/domain/Consult.java
  src/main/java/com/example/sharemind/letter/application/LetterService.java
  src/main/java/com/example/sharemind/letter/application/LetterServiceImpl.java
  src/main/java/com/example/sharemind/letter/content/LetterStatus.java
  src/main/java/com/example/sharemind/letter/domain/Letter.java
  src/main/java/com/example/sharemind/letter/dto/response/LetterGetResponse.java
  src/main/java/com/example/sharemind/letterMessage/content/LetterMessageType.java
Labels: feature

#88 feat: 구매자 페이지 마인더 프로필 조회 구현
  src/main/java/com/example/sharemind/counselor/application/CounselorService.java
  src/main/java/com/example/sharemind/counselor/application/CounselorServiceImpl.java
  src/main/java/com/example/sharemind/counselor/dto/response/CounselorGetMinderProfileResponse.java
  src/main/java/com/example/sharemind/counselor/presentation/CounselorController.java
Labels: feature

#90 feat: 구매자 닉네임 조회 구현
  src/main/java/com/example/sharemind/customer/application/CustomerService.java
  src/main/java/com/example/sharemind/customer/application/CustomerServiceImpl.java
  src/main/java/com/example/sharemind/customer/presentation/CustomerController.java
Labels: feature

#91 feat: 찜하기 api 구현
  src/main/java/com/example/sharemind/counselor/application/CounselorService.java
  src/main/java/com/example/sharemind/counselor/application/CounselorServiceImpl.java
  src/main/java/com/example/sharemind/counselor/dto/response/CounselorGetWishListResponse.java
  src/main/java/com/example/sharemind/global/common/BaseEntity.java
  src/main/java/com/example/sharemind/global/dto/response/ChatLetterGetResponse.java
  src/main/java/com/example/sharemind/global/exception/CustomExceptionHandler.java
  src/main/java/com/example/sharemind/letter/dto/response/LetterGetResponse.java
  src/main/java/com/example/sharemind/searchWord/application/SearchWordServiceImpl.java
  src/main/java/com/example/sharemind/wishList/application/WishListCounselorService.java
  src/main/java/com/example/sharemind/wishList/application/WishListService.java
  src/main/java/com/example/sharemind/wishList/application/WishListServiceImpl.java
  src/main/java/com/example/sharemind/wishList/domain/WishList.java
  src/main/java/com/example/sharemind/wishList/dto/request/WishListGetRequest.java
  src/main/java/com/example/sharemind/wishList/exception/WishListErrorCode.java
  src/main/java/com/example/sharemind/wishList/exception/WishListException.java
  src/main/java/com/example/sharemind/wishList/presentation/WishListController.java
  src/main/java/com/example/sharemind/wishList/repository/WishListRepository.java
  src/main/java/com/example/sharemind/wishlist/application/WishListService.java
  src/main/java/com/example/sharemind/wishlist/application/WishListServiceImpl.java
  src/main/java/com/example/sharemind/wishlist/repository/WishListRepository.java
Labels: feature

#93 feat: 구매자 결제 내역 조회, 어드민 환불 구현
  src/main/java/com/example/sharemind/admin/application/AdminService.java
  src/main/java/com/example/sharemind/admin/application/AdminServiceImpl.java
  src/main/java/com/example/sharemind/admin/dto/response/ConsultGetUnpaidResponse.java
  src/main/java/com/example/sharemind/admin/dto/response/PaymentGetRefundWaitingResponse.java
  src/main/java/com/example/sharemind/admin/presentation/AdminController.java
  src/main/java/com/example/sharemind/consult/domain/Consult.java
  src/main/java/com/example/sharemind/counselor/application/CounselorService.java
  src/main/java/com/example/sharemind/counselor/application/CounselorServiceImpl.java
  src/main/java/com/example/sharemind/counselor/dto/response/CounselorGetMinderProfileResponse.java
  src/main/java/com/example/sharemind/counselor/presentation/CounselorController.java
  src/main/java/com/example/sharemind/global/exception/CustomExceptionHandler.java
  src/main/java/com/example/sharemind/letter/domain/Letter.java
  src/main/java/com/example/sharemind/letter/exception/LetterErrorCode.java
  src/main/java/com/example/sharemind/payment/application/PaymentService.java
  src/main/java/com/example/sharemind/payment/application/PaymentServiceImpl.java
  src/main/java/com/example/sharemind/payment/content/PaymentCustomerStatus.java
  src/main/java/com/example/sharemind/payment/domain/Payment.java
  src/main/java/com/example/sharemind/payment/dto/response/PaymentGetCustomerResponse.java
  src/main/java/com/example/sharemind/payment/exception/PaymentErrorCode.java
  src/main/java/com/example/sharemind/payment/exception/PaymentException.java
  src/main/java/com/example/sharemind/payment/presentation/PaymentController.java
  src/main/java/com/example/sharemind/payment/repository/PaymentRepository.java
  src/main/java/com/example/sharemind/review/application/ReviewService.java
  src/main/java/com/example/sharemind/review/application/ReviewServiceImpl.java
  src/main/java/com/example/sharemind/review/dto/response/ReviewGetResponse.java
  src/main/java/com/example/sharemind/review/presentation/ReviewController.java
  src/main/java/com/example/sharemind/wishList/application/WishListCounselorService.java
  src/main/java/com/example/sharemind/wishList/repository/WishListRepository.java
Labels: feature

#96 feat: 처음 채팅 연결했을 때 user info 넘겨주는 로직 생성
  src/main/java/com/example/sharemind/chat/application/ChatService.java
  src/main/java/com/example/sharemind/chat/application/ChatServiceImpl.java
  src/main/java/com/example/sharemind/chat/dto/response/ChatGetConnectResponse.java
  src/main/java/com/example/sharemind/chat/presentation/ChatController.java
  src/main/resources/static/customer.html
Labels: feature

#97 feat: 일반적인 계정 설정 구현
  src/main/java/com/example/sharemind/auth/application/AuthService.java
  src/main/java/com/example/sharemind/auth/application/AuthServiceImpl.java
  src/main/java/com/example/sharemind/auth/dto/request/AuthGetPasswordMatchRequest.java
  src/main/java/com/example/sharemind/auth/dto/request/AuthQuitRequest.java
  src/main/java/com/example/sharemind/auth/dto/request/AuthSignOutRequest.java
  src/main/java/com/example/sharemind/auth/dto/request/AuthUpdatePasswordRequest.java
  src/main/java/com/example/sharemind/auth/exception/AuthErrorCode.java
  src/main/java/com/example/sharemind/auth/presentation/AuthController.java
  src/main/java/com/example/sharemind/auth/repository/TokenRepository.java
  src/main/java/com/example/sharemind/consult/application/ConsultService.java
  src/main/java/com/example/sharemind/consult/application/ConsultServiceImpl.java
  src/main/java/com/example/sharemind/consult/content/RefundStatus.java
  src/main/java/com/example/sharemind/consult/domain/Consult.java
  src/main/java/com/example/sharemind/consult/repository/ConsultRepository.java
  src/main/java/com/example/sharemind/customer/domain/Customer.java
  src/main/java/com/example/sharemind/customer/domain/Quit.java
  src/main/java/com/example/sharemind/customer/repository/QuitRepository.java
  src/main/java/com/example/sharemind/global/config/SecurityConfig.java
  src/main/java/com/example/sharemind/global/jwt/TokenProvider.java
  src/main/java/com/example/sharemind/payment/application/PaymentService.java
  src/main/java/com/example/sharemind/payment/application/PaymentServiceImpl.java
  src/main/java/com/example/sharemind/payment/content/PaymentCounselorStatus.java
  src/main/java/com/example/sharemind/payment/content/PaymentCustomerStatus.java
  src/main/java/com/example/sharemind/payment/domain/Payment.java
  src/main/java/com/example/sharemind/payment/repository/PaymentRepository.java
Labels: feature

#99 feat: 편지 상담 상대방 닉네임 조회 구현
  src/main/java/com/example/sharemind/counselor/presentation/CounselorController.java
  src/main/java/com/example/sharemind/global/config/SecurityConfig.java
  src/main/java/com/example/sharemind/letter/application/LetterService.java
  src/main/java/com/example/sharemind/letter/application/LetterServiceImpl.java
  src/main/java/com/example/sharemind/letter/exception/LetterErrorCode.java
  src/main/java/com/example/sharemind/letter/presentation/LetterController.java
  src/main/java/com/example/sharemind/letterMessage/application/LetterMessageServiceImpl.java
  src/main/java/com/example/sharemind/letterMessage/dto/response/LetterMessageGetRecentTypeResponse.java
  src/main/java/com/example/sharemind/review/dto/response/ReviewGetResponse.java
  src/main/java/com/example/sharemind/review/dto/response/ReviewGetShortResponse.java
Labels: feature

#102 feat: 진행 중인 상담 구현
  src/main/java/com/example/sharemind/consult/application/ConsultService.java
  src/main/java/com/example/sharemind/consult/application/ConsultServiceImpl.java
  src/main/java/com/example/sharemind/consult/dto/response/ConsultGetOngoingResponse.java
  src/main/java/com/example/sharemind/consult/presentation/ConsultController.java
  src/main/java/com/example/sharemind/global/config/SecurityConfig.java
  src/main/java/com/example/sharemind/global/constants/Constants.java
  src/main/java/com/example/sharemind/global/dto/response/ChatLetterGetResponse.java
  src/main/java/com/example/sharemind/letter/application/LetterConsultService.java
  src/main/java/com/example/sharemind/letter/dto/response/LetterGetOngoingResponse.java
  src/main/java/com/example/sharemind/letter/repository/LetterRepository.java
  src/main/java/com/example/sharemind/letterMessage/dto/response/LetterMessageGetResponse.java
Labels: feature

#104 fix: jwt 인가 여부에 따른 서비스 호출 수정
  src/main/java/com/example/sharemind/counselor/application/CounselorService.java
  src/main/java/com/example/sharemind/counselor/application/CounselorServiceImpl.java
  src/main/java/com/example/sharemind/counselor/presentation/CounselorController.java
Labels: fix

#106 fix: searchword jwt 인증 부분 해결
  src/main/java/com/example/sharemind/global/config/SecurityConfig.java
  src/main/java/com/example/sharemind/searchWord/application/SearchWordService.java
  src/main/java/com/example/sharemind/searchWord/application/SearchWordServiceImpl.java
  src/main/java/com/example/sharemind/searchWord/presentation/SearchWordController.java
Labels: fix
