Repository sharemindteam/sharemind-server, pull requests merged in 2024-08, with the labels that each got.

#240 chore: codeowner 설정
  .github/CODEOWNERS
Labels: chore

#237 feat: 어드민 페이지 상담사, 사용자 이메일 정보 추가
  src/main/java/com/example/sharemind/admin/application/AdminServiceImpl.java
  src/main/java/com/example/sharemind/admin/dto/response/ConsultGetUnpaidResponse.java
  src/main/java/com/example/sharemind/admin/dto/response/CounselorGetByNicknameOrEmailResponse.java
  src/main/java/com/example/sharemind/admin/dto/response/PaymentGetRefundWaitingResponse.java
  src/main/java/com/example/sharemind/admin/dto/response/PaymentGetSettlementOngoingResponse.java
  src/main/java/com/example/sharemind/admin/dto/response/PostGetUnpaidPrivateResponse.java
  src/main/java/com/example/sharemind/counselor/application/CounselorServiceImpl.java
  src/main/java/com/example/sharemind/counselor/domain/Counselor.java
  src/main/java/com/example/sharemind/customer/domain/Customer.java
Labels: feature

#239 fix: 들을 준비가 된 마인더들 empty일 때 랜덤 반환하기
  src/main/java/com/example/sharemind/counselor/application/CounselorService.java
  src/main/java/com/example/sharemind/counselor/application/CounselorServiceImpl.java
  src/main/java/com/example/sharemind/counselor/content/CounselorListSortType.java
  src/main/java/com/example/sharemind/counselor/dto/response/CounselorGetListResponse.java
  src/main/java/com/example/sharemind/counselor/dto/response/CounselorGetRandomListResponse.java
  src/main/java/com/example/sharemind/counselor/presentation/CounselorController.java
Labels: fix

#241 feat: 테스트 서버 분리 위한 github actions workflow 설정 추가
  .github/workflows/deploy_prod.yml
  .github/workflows/deploy_test.yml
  src/main/java/com/example/sharemind/global/config/SwaggerConfig.java
Labels: feature

#242 feat: 마인더 프로필 입력 시 전화번호 추가
  src/main/java/com/example/sharemind/admin/dto/response/ConsultGetUnpaidResponse.java
  src/main/java/com/example/sharemind/admin/dto/response/CounselorGetByNicknameOrEmailResponse.java
  src/main/java/com/example/sharemind/admin/dto/response/PaymentGetRefundWaitingResponse.java
  src/main/java/com/example/sharemind/admin/dto/response/PaymentGetSettlementOngoingResponse.java
  src/main/java/com/example/sharemind/counselor/application/CounselorServiceImpl.java
  src/main/java/com/example/sharemind/counselor/domain/Counselor.java
  src/main/java/com/example/sharemind/counselor/domain/ProfileRecord.java
  src/main/java/com/example/sharemind/counselor/dto/request/CounselorUpdateProfileRequest.java
Labels: feature

#246 fix: 상담사 전화번호 중복 예외 처리
  src/main/java/com/example/sharemind/counselor/application/CounselorServiceImpl.java
  src/main/java/com/example/sharemind/counselor/exception/CounselorErrorCode.java
  src/main/java/com/example/sharemind/counselor/presentation/CounselorController.java
  src/main/java/com/example/sharemind/counselor/repository/CounselorRepository.java
Labels: fix

#248 release: 상담사 전화번호 필드 메인 서버 배포
  src/main/java/com/example/sharemind/admin/dto/response/ConsultGetUnpaidResponse.java
  src/main/java/com/example/sharemind/admin/dto/response/CounselorGetByNicknameOrEmailResponse.java
  src/main/java/com/example/sharemind/admin/dto/response/PaymentGetRefundWaitingResponse.java
  src/main/java/com/example/sharemind/admin/dto/response/PaymentGetSettlementOngoingResponse.java
  src/main/java/com/example/sharemind/counselor/application/CounselorServiceImpl.java
  src/main/java/com/example/sharemind/counselor/domain/Counselor.java
  src/main/java/com/example/sharemind/counselor/domain/ProfileRecord.java
  src/main/java/com/example/sharemind/counselor/dto/request/CounselorUpdateProfileRequest.java
  src/main/java/com/example/sharemind/counselor/dto/response/CounselorGetProfileResponse.java
  src/main/java/com/example/sharemind/counselor/exception/CounselorErrorCode.java
  src/main/java/com/example/sharemind/counselor/presentation/CounselorController.java
  src/main/java/com/example/sharemind/counselor/repository/CounselorRepository.java
Labels: release

#249 release: profileRecord 엔티티에 생성일자, 수정일자 추가
  src/main/java/com/example/sharemind/counselor/domain/ProfileRecord.java
Labels: release

#250 feat: 결제 외부 api 연결 및 플로우 구현
  build.gradle
  src/main/java/com/example/sharemind/admin/application/AdminServiceImpl.java
  src/main/java/com/example/sharemind/chat/application/ChatService.java
  src/main/java/com/example/sharemind/chat/application/ChatServiceImpl.java
  src/main/java/com/example/sharemind/consult/application/ConsultService.java
  src/main/java/com/example/sharemind/consult/application/ConsultServiceImpl.java
  src/main/java/com/example/sharemind/consult/domain/Consult.java
  src/main/java/com/example/sharemind/consult/dto/request/ConsultCreateRequest.java
  src/main/java/com/example/sharemind/consult/presentation/ConsultController.java
  src/main/java/com/example/sharemind/global/config/SecurityConfig.java
  src/main/java/com/example/sharemind/global/exception/CustomExceptionHandler.java
  src/main/java/com/example/sharemind/payApp/application/PayAppService.java
  src/main/java/com/example/sharemind/payApp/application/PayAppServiceImpl.java
  src/main/java/com/example/sharemind/payApp/content/PayMethod.java
  src/main/java/com/example/sharemind/payApp/exception/PayAppErrorCode.java
  src/main/java/com/example/sharemind/payApp/exception/PayAppException.java
  src/main/java/com/example/sharemind/payApp/presentation/PayAppController.java
  src/main/java/com/example/sharemind/payment/domain/Payment.java
  src/main/java/com/example/sharemind/post/application/PostService.java
  src/main/java/com/example/sharemind/post/application/PostServiceImpl.java
  src/main/java/com/example/sharemind/post/domain/Post.java
  src/main/java/com/example/sharemind/post/dto/request/PostCreateRequest.java
  src/main/java/com/example/sharemind/post/presentation/PostController.java
Labels: feature

#251 fix: 결제 확인 요청 파라미터 방식 수정
  src/main/java/com/example/sharemind/payApp/application/PayAppService.java
  src/main/java/com/example/sharemind/payApp/application/PayAppServiceImpl.java
  src/main/java/com/example/sharemind/payApp/dto/request/ConfirmPayRequest.java
  src/main/java/com/example/sharemind/payApp/presentation/PayAppController.java
Labels: fix

#253 fix: 결제 확인 api 요청에 맞게 로직 수정
  src/main/java/com/example/sharemind/consult/domain/Consult.java
  src/main/java/com/example/sharemind/payApp/application/PayAppService.java
  src/main/java/com/example/sharemind/payApp/application/PayAppServiceImpl.java
  src/main/java/com/example/sharemind/payApp/dto/request/ConfirmPayRequest.java
  src/main/java/com/example/sharemind/payApp/exception/PayAppErrorCode.java
  src/main/java/com/example/sharemind/payApp/presentation/PayAppController.java
  src/main/java/com/example/sharemind/payment/application/PaymentService.java
  src/main/java/com/example/sharemind/payment/application/PaymentServiceImpl.java
  src/main/java/com/example/sharemind/payment/domain/Payment.java
  src/main/java/com/example/sharemind/payment/repository/PaymentRepository.java
  src/main/java/com/example/sharemind/post/application/PostService.java
  src/main/java/com/example/sharemind/post/application/PostServiceImpl.java
  src/main/java/com/example/sharemind/post/domain/Post.java
  src/main/java/com/example/sharemind/post/repository/PostRepository.java
Labels: fix

#254 refactor: 결제 요청 창으로 리다이렉트 되도록 수정
  src/main/java/com/example/sharemind/consult/presentation/ConsultController.java
  src/main/java/com/example/sharemind/payApp/presentation/PayAppController.java
  src/main/java/com/example/sharemind/post/presentation/PostController.java
Labels: refactor

#256 feat: sms 발송 api 연동
  src/main/java/com/example/sharemind/admin/application/AdminService.java
  src/main/java/com/example/sharemind/admin/application/AdminServiceImpl.java
  src/main/java/com/example/sharemind/admin/presentation/AdminController.java
  src/main/java/com/example/sharemind/payApp/application/PayAppServiceImpl.java
  src/main/java/com/example/sharemind/sms/application/SmsService.java
  src/main/java/com/example/sharemind/sms/application/SmsServiceImpl.java
  src/main/java/com/example/sharemind/sms/dto/response/SmsGetResponse.java
Labels: feature
