Repository sharemindteam/sharemind-server, pull requests merged in 2024-11, with the labels that each got.

#274 fix: 상담 수수료 로직 및 DB 테이블 구조 수정
  src/main/java/com/example/sharemind/counselor/domain/Settlement.java
  src/main/java/com/example/sharemind/global/constants/Constants.java
  src/main/java/com/example/sharemind/payment/application/PaymentServiceImpl.java
  src/main/java/com/example/sharemind/payment/domain/Payment.java
  src/main/java/com/example/sharemind/payment/dto/response/PaymentGetCounselorResponse.java
Labels: fix

#275 feat: 어드민 결제 내역 api 추가
  src/main/java/com/example/sharemind/admin/application/AdminService.java
  src/main/java/com/example/sharemind/admin/application/AdminServiceImpl.java
  src/main/java/com/example/sharemind/admin/dto/response/ConsultGetUnpaidResponse.java
  src/main/java/com/example/sharemind/admin/dto/response/PostGetUnpaidPrivateResponse.java
  src/main/java/com/example/sharemind/admin/presentation/AdminController.java
  src/main/java/com/example/sharemind/consult/application/ConsultService.java
  src/main/java/com/example/sharemind/consult/application/ConsultServiceImpl.java
  src/main/java/com/example/sharemind/consult/repository/ConsultRepository.java
  src/main/java/com/example/sharemind/post/application/PostService.java
  src/main/java/com/example/sharemind/post/application/PostServiceImpl.java
  src/main/java/com/example/sharemind/post/repository/PostRepository.java
Labels: feature

#276 release: 서버 배포
  src/main/java/com/example/sharemind/admin/application/AdminService.java
  src/main/java/com/example/sharemind/admin/application/AdminServiceImpl.java
  src/main/java/com/example/sharemind/admin/dto/response/ConsultGetUnpaidResponse.java
  src/main/java/com/example/sharemind/admin/dto/response/PostGetUnpaidPrivateResponse.java
  src/main/java/com/example/sharemind/admin/presentation/AdminController.java
  src/main/java/com/example/sharemind/consult/application/ConsultService.java
  src/main/java/com/example/sharemind/consult/application/ConsultServiceImpl.java
  src/main/java/com/example/sharemind/consult/repository/ConsultRepository.java
  src/main/java/com/example/sharemind/counselor/domain/Settlement.java
  src/main/java/com/example/sharemind/global/constants/Constants.java
  src/main/java/com/example/sharemind/payment/application/PaymentService.java
  src/main/java/com/example/sharemind/payment/application/PaymentServiceImpl.java
  src/main/java/com/example/sharemind/payment/domain/Payment.java
  src/main/java/com/example/sharemind/payment/dto/response/PaymentGetCounselorResponse.java
  src/main/java/com/example/sharemind/payment/dto/response/PaymentGetCounselorResponses.java
  src/main/java/com/example/sharemind/payment/dto/response/PaymentGetCustomerResponse.java
  src/main/java/com/example/sharemind/payment/presentation/PaymentController.java
  src/main/java/com/example/sharemind/post/application/PostService.java
  src/main/java/com/example/sharemind/post/application/PostServiceImpl.java
  src/main/java/com/example/sharemind/post/repository/PostRepository.java
Labels: release
